/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack_copier;

/**
 *
 * @author YASSALIE
 */
public class GererLaTaillle extends javax.swing.JFrame {

    /**
     * Creates new form GererLaTaillle
     */
    public GererLaTaillle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG = new javax.swing.ButtonGroup();
        jlligne = new javax.swing.JLabel();
        jrbSmall = new javax.swing.JRadioButton();
        JrbMedium = new javax.swing.JRadioButton();
        JrbLarge = new javax.swing.JRadioButton();
        jrbXl = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transformer le texte dans un label");

        jlligne.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlligne.setText("Choisissez une taille afin de transformer la taille de ce texte");

        btnG.add(jrbSmall);
        jrbSmall.setText("Small");
        jrbSmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSmallActionPerformed(evt);
            }
        });

        btnG.add(JrbMedium);
        JrbMedium.setText("Medium");
        JrbMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrbMediumActionPerformed(evt);
            }
        });

        btnG.add(JrbLarge);
        JrbLarge.setText("large");
        JrbLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrbLargeActionPerformed(evt);
            }
        });

        btnG.add(jrbXl);
        jrbXl.setText("Extra Large");
        jrbXl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbXlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jrbSmall)
                        .addGap(31, 31, 31)
                        .addComponent(JrbMedium)
                        .addGap(18, 18, 18)
                        .addComponent(JrbLarge)
                        .addGap(18, 18, 18)
                        .addComponent(jrbXl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlligne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jlligne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbSmall)
                    .addComponent(JrbMedium)
                    .addComponent(JrbLarge)
                    .addComponent(jrbXl))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbSmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSmallActionPerformed
        // TODO add your handling code here:
        jlligne.setFont(new java.awt.Font("Tahoma", 0, 10));
        
 
    }//GEN-LAST:event_jrbSmallActionPerformed

    private void JrbMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrbMediumActionPerformed
        // TODO add your handling code here:
        jlligne.setFont(new java.awt.Font("Tahoma", 0, 12));
    }//GEN-LAST:event_JrbMediumActionPerformed

    private void JrbLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrbLargeActionPerformed
        // TODO add your handling code here:
        jlligne.setFont(new java.awt.Font("Tahoma", 0, 14));
    }//GEN-LAST:event_JrbLargeActionPerformed

    private void jrbXlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbXlActionPerformed
        // TODO add your handling code here:
        jlligne.setFont(new java.awt.Font("Tahoma", 0, 16));
    }//GEN-LAST:event_jrbXlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GererLaTaillle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GererLaTaillle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GererLaTaillle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GererLaTaillle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GererLaTaillle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JrbLarge;
    private javax.swing.JRadioButton JrbMedium;
    private javax.swing.ButtonGroup btnG;
    private javax.swing.JLabel jlligne;
    private javax.swing.JRadioButton jrbSmall;
    private javax.swing.JRadioButton jrbXl;
    // End of variables declaration//GEN-END:variables
}
